package dev.rifaii.http.spec;


//TODO: VALIDATE. this was generated by GPT
public enum HttpStatusCode {

    // 1xx Informational
    CONTINUE(100, "Continue"),
    SWITCHING_PROTOCOLS(101, "Switching Protocols"),
    PROCESSING(102, "Processing"),
    EARLY_HINTS(103, "Early Hints"),

    // 2xx Success
    OK(200, "OK"),
    CREATED(201, "Created"),
    ACCEPTED(202, "Accepted"),
    NON_AUTHORITATIVE_INFORMATION(203, "Non-Authoritative Information"),
    NO_CONTENT(204, "No Content"),
    RESET_CONTENT(205, "Reset Content"),
    PARTIAL_CONTENT(206, "Partial Content"),
    MULTI_STATUS(207, "Multi-Status"),
    ALREADY_REPORTED(208, "Already Reported"),
    IM_USED(226, "IM Used"),

    // 3xx Redirection
    MULTIPLE_CHOICES(300, "Multiple Choices"),
    MOVED_PERMANENTLY(301, "Moved Permanently"),
    FOUND(302, "Found"),
    SEE_OTHER(303, "See Other"),
    NOT_MODIFIED(304, "Not Modified"),
    USE_PROXY(305, "Use Proxy"),
    TEMPORARY_REDIRECT(307, "Temporary Redirect"),
    PERMANENT_REDIRECT(308, "Permanent Redirect"),

    // 4xx Client Error
    BAD_REQUEST(400, "Bad Request"), //Implemented
    UNAUTHORIZED(401, "Unauthorized"), //TODO
    PAYMENT_REQUIRED(402, "Payment Required"), // NOT mandatory https://datatracker.ietf.org/doc/html/rfc9110#name-402-payment-required
    FORBIDDEN(403, "Forbidden"), //TODO
    NOT_FOUND(404, "Not Found"), //Implemented
    METHOD_NOT_ALLOWED(405, "Method Not Allowed"), //Implemented
    NOT_ACCEPTABLE(406, "Not Acceptable"), //TODO
    PROXY_AUTHENTICATION_REQUIRED(407, "Proxy Authentication Required"), //not sure yet https://datatracker.ietf.org/doc/html/rfc9110#name-407-proxy-authentication-re
    REQUEST_TIMEOUT(408, "Request Timeout"), //TODO
    CONFLICT(409, "Conflict"), // Not needed
    GONE(410, "Gone"), //Not needed
    LENGTH_REQUIRED(411, "Length Required"), //TODO
    PRECONDITION_FAILED(412, "Precondition Failed"), //
    PAYLOAD_TOO_LARGE(413, "Payload Too Large"),
    URI_TOO_LONG(414, "URI Too Long"),
    UNSUPPORTED_MEDIA_TYPE(415, "Unsupported Media Type"),
    RANGE_NOT_SATISFIABLE(416, "Range Not Satisfiable"),
    EXPECTATION_FAILED(417, "Expectation Failed"),
    IM_A_TEAPOT(418, "I'm a teapot"),
    MISDIRECTED_REQUEST(421, "Misdirected Request"),
    UNPROCESSABLE_ENTITY(422, "Unprocessable Entity"),
    LOCKED(423, "Locked"),
    FAILED_DEPENDENCY(424, "Failed Dependency"),
    TOO_EARLY(425, "Too Early"),
    UPGRADE_REQUIRED(426, "Upgrade Required"),
    PRECONDITION_REQUIRED(428, "Precondition Required"),
    TOO_MANY_REQUESTS(429, "Too Many Requests"),
    REQUEST_HEADER_FIELDS_TOO_LARGE(431, "Request Header Fields Too Large"),
    UNAVAILABLE_FOR_LEGAL_REASONS(451, "Unavailable For Legal Reasons"),

    // 5xx Server Error
    INTERNAL_SERVER_ERROR(500, "Internal Server Error"),
    NOT_IMPLEMENTED(501, "Not Implemented"), //TODO
    BAD_GATEWAY(502, "Bad Gateway"), //NOT a proxy https://datatracker.ietf.org/doc/html/rfc9110#name-502-bad-gateway
    SERVICE_UNAVAILABLE(503, "Service Unavailable"), //NOT mandatory https://datatracker.ietf.org/doc/html/rfc9110#status.503
    GATEWAY_TIMEOUT(504, "Gateway Timeout"), //NOT a proxy https://datatracker.ietf.org/doc/html/rfc9110#name-504-gateway-timeout
    HTTP_VERSION_NOT_SUPPORTED(505, "HTTP Version Not Supported"), //IMPLEMENTED
    VARIANT_ALSO_NEGOTIATES(506, "Variant Also Negotiates"),
    INSUFFICIENT_STORAGE(507, "Insufficient Storage"),
    LOOP_DETECTED(508, "Loop Detected"),
    NOT_EXTENDED(510, "Not Extended"),
    NETWORK_AUTHENTICATION_REQUIRED(511, "Network Authentication Required");

    private final int code;
    private final String description;

    HttpStatusCode(int code, String description) {
        this.code = code;
        this.description = description;
    }

    public int getCode() {
        return code;
    }

    public String getDescription() {
        return description;
    }

    @Override
    public String toString() {
        return code + " " + description;
    }
}

